Update User Guide
AY2021S2-CS2103T-W13-4/tp pull request #114
Opened 2021-04-01 15:15 UTC by tsh22

2021-04-01 15:49 UTC, goatygoatygoat requested changes

2021-04-01 15:49 UTC, goatygoatygoat commented on docs/UserGuide.md
> +interactions rely on typing commands as user inputs.
I wrote a small intro last time:

Welcome to the User Guide of **Teaching Assistant**!

Are you a JC/Secondary school teacher, having troubles keeping track of all your consultations, meetings and your students' contacts? No worries! Our application, **Teaching Assistant** will provide an all-in-one platform for you to organise your entries _(tasks and schedules)_ and contacts!

Teaching Assistant mainly uses a Command Line Interface (CLI). This means that a user can use the application by typing into a Command Box. For users who type fast, they can use this application more efficiently than other applications that heavily use Graphical User Interface (GUI), where a user uses the application by interacting with graphical features such as buttons.

If you are interested, jump to [Quick Start](#quick-start) to learn how to learn how to start using **Teaching Assistant**.

2021-04-01 15:49 UTC, goatygoatygoat commented on docs/UserGuide.md
>      - [Contact](#adding-a-contact)
Can add hyperlinks to each command under the Contact category, same for Entry category.

2021-04-01 15:49 UTC, goatygoatygoat commented on docs/UserGuide.md
Can add screenshots from our demo under each feature (but is optional for now)

2021-04-01 15:49 UTC, goatygoatygoat commented on docs/UserGuide.md
Change the pic to our actual Ui.

2021-04-01 15:49 UTC, goatygoatygoat commented on docs/UserGuide.md
> +* Persons matching at least one keyword will be returned (i.e. OR search). E.g. `Hans Bo` will return `Hans Gruber`
I've changed the implementation such that `Hans Bo` will only return `Hans Bo`!

2021-04-01 15:49 UTC, goatygoatygoat commented on docs/UserGuide.md
> +* `find alex david` returns `Alex Yeoh`, `David Li`
Will not return anything unless there is a person called `alex david`

2021-04-01 15:55 UTC, lrj689 approved these changes

2021-04-01 16:10 UTC, goatygoatygoat commented on docs/UserGuide.md
>  1. Copy the file to the folder you want to use as the *home folder* for your AddressBook.
for your Teaching Assistant

2021-04-02 10:48 UTC, goatygoatygoat approved these changes

2021-04-02 13:22 UTC, KevinLohJunYong approved these changes

2021-04-02 13:40 UTC, merged