Branch delete index
AY2021S2-CS2103T-W13-4/tp pull request #184
Opened 2021-04-06 14:34 UTC by lrj689

Parameter for edelete changed from name to index, added test for edelete aswell as other testing utilities

2021-04-06 14:49 UTC, nicholastanvis requested changes

2021-04-06 14:49 UTC, nicholastanvis commented on src/main/java/seedu/address/commons/core/Messages.java
> +    public static final String MESSAGE_NO_SUCH_ENTRY = "The entry index provided is invalid";
might wanna change this to MESSAGE_INVALID_ENTRY_INDEX

2021-04-06 14:49 UTC, nicholastanvis commented on src/main/java/seedu/address/logic/commands/DeleteEntryCommand.java
> + * Deletes an entry identified using it's displayed index from teaching assistant.
should be "its"
xd

if can, capitalise Teaching Assistant

2021-04-06 14:49 UTC, nicholastanvis commented on src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
> +import static seedu.address.testutil.TypicalIndexes.INDEX_FIRST;
the plural of index is indices

2021-04-06 14:49 UTC, nicholastanvis commented on src/test/java/seedu/address/testutil/EntryBuilder.java
> +    public static final String DEFAULT_END_DATE = "2021-04-05 19:00";
should we have DEFAULT_TAGS so we can feed it into the ctor in line 30?

2021-04-06 14:49 UTC, nicholastanvis commented on src/test/java/seedu/address/testutil/TypicalEntries.java
> +    private TypicalEntries() {}
what is this line for?

2021-04-06 14:49 UTC, nicholastanvis commented on src/test/java/seedu/address/testutil/TypicalIndexes.java
> +    public static final Index INDEX_THIRD = Index.fromOneBased(3);
based and redpilled

2021-04-06 15:28 UTC, goatygoatygoat approved these changes

2021-04-06 23:02 UTC, nicholastanvis approved these changes

2021-04-07 07:26 UTC, tsh22 approved these changes

2021-04-07 11:47 UTC, merged