Branch entry class tests
AY2021S2-CS2103T-W13-4/tp pull request #196
Opened 2021-04-09 12:36 UTC by lrj689

2021-04-09 13:50 UTC, nicholastanvis approved these changes

2021-04-10 02:25 UTC, goatygoatygoat requested changes

2021-04-10 02:25 UTC, goatygoatygoat commented on src/test/java/seedu/address/model/entry/EntryNameTest.java
> +        assertTrue(Name.isValidName("peter jack")); // alphabets only
The names given for these tests should sound more like entry names and not contact names, same for the assertFalse statements above.

2021-04-10 02:25 UTC, goatygoatygoat commented on src/test/java/seedu/address/model/entry/EntryNameTest.java
> +import seedu.address.model.person.Name;
Remove all traces of person in this class.

2021-04-10 03:03 UTC, tsh22 approved these changes

2021-04-10 03:08 UTC, goatygoatygoat approved these changes

2021-04-10 03:08 UTC, merged